name: CI Integration Tests
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - 'master'

jobs:
  test:
    strategy:
      matrix:
        python: ['3.8', '3.9', '3.10']
    runs-on: ubuntu-latest
    name: Functional test
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Define env name
        id: define-environment-name
        run: |
          echo "env-name=feast-teradata-ci-$(date +%s%N)" >> $GITHUB_OUTPUT

      - name: Start test environment
        id: start-test-environment
        run: |
          RESULT=$(curl --location --request POST 'https://api.clearscape.teradata.com/environments' \
            --header "Authorization: Bearer $CSAE_TOKEN" \
            --header 'Content-Type: application/json' \
            --data-raw "{
                \"name\": \"$CSAE_ENV_NAME\",
                \"region\": \"us-central\",
                \"password\": \"$CSAE_ENV_PASSWORD\"
            }")
          DB_HOST=$(echo $RESULT | jq -r '.dnsName')
          echo "db-host=$DB_HOST" >> $GITHUB_OUTPUT
        env:
          CSAE_TOKEN: '${{ secrets.CSAE_TOKEN }}'
          CSAE_ENV_PASSWORD: '${{ secrets.CSAE_ENV_PASSWORD }}'
          CSAE_ENV_NAME: '${{ steps.define-environment-name.outputs.env-name }}'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Build and install package
        run: |
          python setup.py sdist bdist_wheel
          pip install dist/*.whl

      - name: Run test workflow
        run: |
          feast-td init-repo
          cd test_repo && python test_workflow.py
        env:
          CI_RUNNING: 'true'
          CI_TD_HOST: '${{ steps.start-test-environment.outputs.dbc-host }}'
          CI_TD_USER: 'demo_user'
          CI_TD_PASSWORD: '${{ secrets.CSAE_ENV_PASSWORD }}'
          CI_TD_DATABASE: 'demo_user'
          CI_TD_LOGMECH: 'TDNEGO'
          CI_FEAST_REPO_NAME: 'test_repo'

      - name: Delete test environment
        if: always()
        run: |
          curl --location --request DELETE "https://api.clearscape.teradata.com/environments/$CSAE_ENV_NAME" \
            --header "Authorization: Bearer $CSAE_TOKEN"
        env:
          CSAE_TOKEN: '${{ secrets.CSAE_TOKEN }}'
          CSAE_ENV_NAME: '${{ steps.define-environment-name.outputs.env-name }}'
